### ISSUE TITLE
Question: easiest way to find nodes of Delaunay triangle belonging to point p

### ISSUE THREAD

**Issue by 1kastner** [jmespadero/pyDelaunay2D#2]
Given a point p, how can I use the Delaunay2D class in the best way to find the Delaunay triangle it is in? It rather looks like that this feature is not supported directly -- the Delaunay2D.inCircleRobust(self, tri, p) method is not suitable as the circle is larger than the triangle and most of the remaining methods help to export the internal state of the class once everything is added. So I guess a new function is needed for that. Is there something in the pipeline and will be published soon or can I try out and maybe create a pull request for that feature?

**Comment by jmespadero** [comment]
For DT you don't test if a point is inside a triangle, but inside a triangle's circumcircle.

The test is easy to write, but I shouldn't if I want to keep the code clean.

See https://www.cs.cmu.edu/~quake/robust.html to see a robust way to determine if a point p is on the left side of a segment. If your point p is on the same side of the three sides of you triangle, then the point is inside your triangle.

**Comment by 1kastner** [comment]
Yes, another good website can be found at http://blackpawn.com/texts/pointinpoly/default.html with some implementation hints.

I think this functionality is quite crucial as the reason why you want Delaunay triangles in the first place is most likely that you want to spatially interpolate something and you need the three corners in order to do so. So I believe it could be a great addition to the current project but keeping the code clean is also important, I agree.
