### ISSUE TITLE
Some points can't be make up to triangles well 

### ISSUE THREAD

**Issue by Tancen** [jmespadero/pyDelaunay2D#4]
I have been added some points into 'dt' such '[[331, 176],[235, 221],[350, 318],[379, 245]]' to make up triangles, And i got a result as '[(3, 2, 1), (3, 1, 0)]'. It's not i want. Because have a cross be produced.

**Comment by jmespadero** [comment]
The solution [(3, 1, 0), (3, 2, 1)] seems correct to me... 

![Screenshot from 2019-08-16 10:44:01](https://user-images.githubusercontent.com/6451497/63155667-4ff6d980-c013-11e9-85a1-45d454e13d04.png)

Why is not OK for you?

**Comment by Tancen** [comment]
Sorry, I forget to increase the radius
